### ISSUE TITLE
Deploy to Heroku didn't work with error message.

### ISSUE THREAD

**Issue by yutatt** [seratch/deepl-for-slack#11] opened 2022-01-29 16:50 UTC
Cannot deploy new app from your link and it shows this error below.
"We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy."

**Comment by ingtk** [comment] 2022-02-03 03:52
I had the same error and solved it as follows.

refer: https://github.com/developeranaz/Mega-index-heroku/issues/28#issuecomment-1009749327

---

1. fork this repository
2. then deploy using the below similar link
3. https://heroku.com/deploy?template=https://github.com/YOURGITHUBUSERNAME/deepl-for-slack/tree/master

replace YOURGITHUBUSERNAME to your own github username

**Comment by seratch** [comment] 2022-02-13 12:08
Thanks for reporting this issue. 

I myself am not able to reproduce this issue with the "Deploy to Heroku" button in any other repositories. This indicates that the error described here can occur if your Heroku account is under specific Salesforce security policies. My testing Heroku account is a personal one and it does not have any specific settings. I'm guessing that this is why I cannot reproduce your situation.

If my speculation here is correct, as mentioned above, forking this repo and deploying it to Heroku would be a reasonable workaround.

Let me close this issue after waiting for others' comments for a while.

**Closed** 2022-12-26 23:46 UTC
